### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by NikitaSemenov** [renskiy/fabricio#63]
need support for python3

**Comment by renskiy** [comment]
Due to [Fabric's development roadmap](http://www.fabfile.org/roadmap.html) there are no any plans on implementing Python 3 support for Fabric 1.x. This caused by incompatibility of Python 2.5 (which is still supported by Fabric 1.x) and Python 3.

So, the only Fabric version which will work with Python 3 is 2.x but it hasn't been released yet.

**Comment by supadrupa** [comment]
https://github.com/mathiasertl/fabric/

**Comment by renskiy** [comment]
It's OK to use [Fabric3](https://github.com/mathiasertl/fabric/). But I found [bug](https://github.com/mathiasertl/fabric/issues/38) with `abort()` method there. It isn't a blocker but user may suddenly face with it while getting an unreadable error.
